import type { Metadata } from "next";
import { Nobile } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Header/Nav/Nav";
const nobile = Nobile({ subsets: ["latin"], weight: "400", variable: "--font-nobile" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body className={nobile.className} >
        <Nav />

        {children}

      </body>
    </html>
  );
}
